const errorHandler = require('../utils/errorHandler')
module.exports.getPersonal = async (res, req) => {
    try{

    } catch(e){
        errorHandler(res,e)
    }

}

module.exports.addBook = async (res, req) => {
    try{

    } catch(e){
        errorHandler(res,e)
    }

}